### ISSUE TITLE
Biomes dont reset

### ISSUE THREAD

**Issue by Lelebees** [mpeij/python-survival-game#1]
Biomes resetten niet :( 
ook werkt notepad++ niet meer goed en ik kan het niet opnieuw instellen
is het goed als ik een time import toevoeg(daarmee lukt het hopelijk wel)

**Comment by Lelebees** [comment]
import heb ik van deze pagina
https://stackoverflow.com/questions/510348/how-can-i-make-a-time-delay-in-python

**Comment by Lelebees** [comment]
met reset bedoel is newTerrain = False werkt niet

**Comment by mpeij** [comment]
fixed ik heb het biomegen bestand in de main_file bestand gezet en het als functie gebruikt. Hij werkt nu wel

**Comment by Lelebees** [comment]
Wauw, daar had ik niet eens aan gedacht

Op do 27 sep. 2018 20:32 schreef mpeij <notifications@github.com>:
